---
title: "Data Exploration Analysis"
author: "Danielle Watkins"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r}
load("data/clean_trends.RData")
```

```{r}
library(tidyverse)
library(purrr)
library(lubridate)
library(fixest)
library(vtable)
```


#Add in some summary statistics for the data. 
```{r}
sumtable(clean_data)
```

```{r}
ggplot(clean_data, mapping = aes(index)) + geom_histogram(bins = 100)
```


```{r}
index_time_graph <- clean_data %>% group_by(monthorweek, high_income) %>% summarize(mean(index))

ggplot(index_time_graph, aes(x = monthorweek, y = `mean(index)`, color = high_income)) + geom_point() + geom_line() + geom_vline(xintercept = as.Date("2015-09-01")) + geom_smooth(method = 'lm')
```
```{r}
clean_data <- clean_data %>% mutate(month = month(monthorweek))
ggplot(clean_data, aes(x = month, y = index)) + geom_col()
```



```{r}
md1 <- feols(index ~ scorecard_exist + high_income + month, data = clean_data)
```

```{r}
wald(md1, c('high_income', 'scorecard_exist'))
etable(md1)
```

Want to get interaction of high_income and scorecard_exist. Also going to add control for seasonality and separate month from the monthorweek variable. 

```{r}
md2 <- feols(index ~ scorecard_exist + high_income + scorecard_exist*high_income + month, data = clean_data)
```

```{r}
wald(md2, c('high_income', 'scorecard_exist'))
etable(md2)
```

```{r}
md3 <- feols(index ~ scorecard_exist + high_income + scorecard_exist*high_income + month | schname, data = clean_data)
```

```{r}
wald(md3, c('high_income', 'scorecard_exist'))
etable(md2, md3)
```

